spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gistest
    hikari:
      username: root
      password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        format_sql: true
        show_sql: true